export const unitList =  [
    { region: 'DRONO', unit: 'DPC BAMENDA EXT' },
    { region: 'DRONO', unit: 'DVC OUEST 1 - BAF' },
    { region: 'DRD', unit: 'DVC DOUALA CENTRE' },
    { region: 'DRD', unit: 'DVC DOUALA OUEST' },
    { region: 'DRD', unit: 'DVC DOUALA SUD' },
    { region: 'DRY', unit: 'DVC YAOUNDE SUD' },
    { region: 'DRY', unit: 'DVC YAOUNDE EST' },
    { region: 'DRSOM', unit: 'DPC MOUNGO' },
    { region: 'DRSOM', unit: 'DVC LIMBE' },
    { region: 'DRNEA', unit: 'DLP EXTREME-NORD' },
    { region: 'DRNEA', unit: 'DLP ADAMAOUA' },
    { region: 'DRSM', unit: 'DPC MBALMAYO' },
    { region: 'DRSANO', unit: 'DPC KRIBI' },
    { region: 'DRC', unit: 'DPC OBALA' },
    { region: 'DRSM', unit: 'DPC SANGMELIMA' },
    { region: 'DRSM', unit: 'DPC EBOLOWA' },
    { region: 'DRONO', unit: 'DVC OUEST 1 NOUN' },
    { region: 'DRONO', unit: 'DVC OUEST 2NHT_NKAM' },
    { region: 'DRONO', unit: 'DVC OUEST 2-MEN_BAMB' },
    { region: 'DRSOM', unit: 'DPC KUMBA' },
    { region: 'DRD', unit: 'DVC DOUALA NORD' },
    { region: 'DRD', unit: 'DVC DOUALA EST' },
];